name = "RHEOSafm"
uuid = "73cac1ca-88b8-4b1f-b66b-ed9b1bd992ce"
authors = ["Alessandra <bonfantiale.ab@gmail.com>", "J Louis Kaplan <jonathanlouiskaplan@outlook.com>", "Alexandre Kabla <ajk61@cam.ac.uk>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
RHEOS = "728860ae-c896-11e8-0b91-0f38ecad5046"
